
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
        integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="/BAIKIEMTRA2/views/assets/css/stylechung.css">
    <!--Khi bạn chạy ứng dụng bắt đầu từ index.php (ở ngoài cùng), đường dẫn này đúng.
Nhưng khi bạn include file theo MVC, file header.php nằm trong views/home/, nên PHP hiểu đường dẫn tính từ index.php (file đang chạy) → có thể sai nếu bạn dùng đường dẫn tương đối không chuẩn.-->
</head>